stages:
  - install
  - test
  - build

cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm ci

test:
  stage: test
  script:
    - npm run test:unit

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
