name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧪 Run unit tests
        run: npm run test

      - name: 🏗️ Build app
        run: npm run build

  # docker-image:
  #   runs-on: ubuntu-latest
  #   needs: build-test

  #   steps:
  #     - uses: actions/checkout@v3

  #     - name: 🔧 Setup Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: 🐳 Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: 📦 Build and push Docker image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: .
  #         push: true
  #         tags: yourusername/conroo-frontend:latest
